nelmio_api_doc:
    documentation:
        info:
            title: Thoth API
            version: 1.0.0
        basePath: '/'

    areas:
        path_patterns:
            - ^/articles
            - ^/websites
