nelmio_api_doc:
    documentation:
        info:
            title: Thoth API
            version: 1.0.0
        basePath: '/'
        securityDefinitions:
            Bearer:
                type: apiKey
                description: Value for the Authorization header
                name: Authorization
                in: header
        security:
            - Bearer: []

    areas:
        path_patterns:
            - ^/articles
            - ^/users
            - ^/websites
