name: CI & CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Run tests
        run: |
          cp phpunit.xml.dist phpunit.xml
          composer test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
      - name: Add Heroku remote
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Rewrite branches
        run: git filter-branch -- --all
      - name: Deploy to Heroku
        run: git push heroku master --force
